package.json
yarn.lock

fixed eslint configuration

---

package.json

fixed package.json merge issue

---

tests/Student.test.js
yarn.lock

fixed yarn.lock and delete console.log from student model test

---

README.md
package.json
yarn.lock

removed mongo-unique-validator and added readme template

---

server/app.js
server/services/auth.js
tests/Assignment.test.js
tests/Student.test.js
tests/Teacher.test.js
tests/User.test.js
tests/authController.test.js
tests/jwt.test.js
tests/testDataFactories.js

Added jwt middleware and refactored tests 
New tests in test/jwt.test.js

Jwt verification + test refactoring

---

apidoc/api_data.js
apidoc/api_data.json
apidoc/api_project.js
apidoc/api_project.json
server/app.js
server/controllers/userController.js
server/models/User.js
server/routes/authRoutes.js
server/routes/userRoutes.js
tests/Student.test.js
tests/Teacher.test.js
tests/User.test.js
tests/testDataFactories.js
tests/userController.test.js

Add user settings api route, refactor model code

---

.eslintrc.json
server/app.js
server/server.js
tests/app.test.js

- [] I have made corresponding changes to the documentation

Heroku deployment

---

apidoc/api_data.js
apidoc/api_data.json
apidoc/api_project.js
apidoc/api_project.json
server/controllers/userController.js

api doc syntax error fix and generated new docs

api doc syntax error fix and generated new docs

---

front-end/src/components/Billing/CheckoutForm.js

fixed the incorrect card info bug and added comments to the code

---

.eslintrc.json
apidoc/api_data.js
apidoc/api_data.json
apidoc/api_project.js
apidoc/api_project.json
server/apidoc_definitions/user.defs.js
server/controllers/userController.js
server/models/User.js
server/routes/userRoutes.js
tests/User.test.js
tests/userController.test.js

- [] I have made corresponding changes to the documentation

Modularize apidoc errors, modify editProfile, add/update user tests

---

front-end/src/components/Assignments/AddAssignment/AddAssignmentForm.js
front-end/src/components/Assignments/AssignmentDetails.js
front-end/src/routes/index.js

- [x ] Bug fix (non-breaking change which fixes an issue)
*Fixed typo
- [x ] I have performed a self-review of my own code

Fixed login typo

---

cypress/integration/frontend_spec.js

added frontend tests for landing, signup, and login pages

---

front-end/src/components/LogIn/LogIn.js
front-end/src/components/LogIn/login.css
front-end/src/components/Signup/SignUp.js
front-end/src/components/Signup/sign-up.css

- [x ] New feature (non-breaking change which adds functionality)
*Visually on screen
- [ x] I have performed a self-review of my own code
- [ x] My changes generate no new warnings

Add selection signup

---

cypress/integration/frontend_spec.js

fixed the signup page input name from username to email

---

apidoc/api_data.js
apidoc/api_data.json
apidoc/api_project.js
apidoc/api_project.json
front-end/src/components/Billing/CheckoutForm.js
front-end/src/components/Menu/Menu.js
front-end/src/components/UserSettings/UserSettings.js
front-end/src/components/UserSettings/userSettings.css
server/controllers/userController.js
server/models/User.js
server/routes/userRoutes.js
tests/User.test.js
tests/userController.test.js

added settings page and connected with the backend to update user information

---

.eslintrc.json
front-end/package.json
front-end/src/actions/index.js
front-end/src/components/LogIn/LogIn.js
front-end/src/components/Signup/Error.js
front-end/src/components/Signup/SignUp.js
front-end/src/index.js
front-end/src/reducers/auth.js
front-end/src/reducers/index.js
front-end/yarn.lock

added redux, redux form and connect with the signup and login functions

---

apidoc/api_data.js
apidoc/api_data.json
apidoc/api_project.js
apidoc/api_project.json
server/controllers/userController.js
server/models/User.js
tests/userController.test.js

…Student, defaults to Student)
modify user registration to allow for role specification (Teacher or Student, defaults to Student)
https://trello.com/c/RDhid6rW/20-modify-authentication-api-to-recognize-the-difference-between-a-student-and-a-teacher

modify user registration (specify role (Teacher, Student))

---

cypress/integration/frontend_spec.js
front-end/src/components/landingpage/mainImage.js

Modified the cypress tests slightly to improve performance and moved sample images to imgur for faster loading (so the tests aren't stalling)

Improve cypress performance

---

front-end/src/actions/index.js
front-end/src/components/Dashboard/InfoDisplay/Billing/CheckoutForm.js

fixed the redux login saving jwt token function and added redirection after transaction succeed

---

front-end/src/components/Dashboard/InfoDisplay/StudentAssignments/StudentAssignments.js
server/models/Assignment.js
tests/Assignment.test.js
tests/testDataFactories.js

added dueDate field to Assignment model and changed the assignment tests

---

front-end/src/components/Dashboard/InfoDisplay/Assignments/AddAssignments/AssignmentForm.js
front-end/src/components/Dashboard/InfoDisplay/Assignments/AssignmentCard/AssignmentCard.js
front-end/src/components/Dashboard/InfoDisplay/Assignments/AssignmentDetails/AssignmentDetails.js
front-end/src/components/Dashboard/InfoDisplay/Assignments/Assignments.js
front-end/src/components/Dashboard/InfoDisplay/InfoDisplay.js
front-end/src/components/Dashboard/InfoDisplay/StudentAssignments/StudentAssignments.js

- [x ] New feature (non-breaking change which adds functionality)
- [x ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
* In the browser
- [ x] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] …

Teacher assignment page

---

front-end/src/actions/index.js
front-end/src/components/Dashboard/InfoDisplay/UserSettings/UserSettings.js

Removed the redirection in user settings page if token not exist

---

front-end/src/actions/index.js
front-end/src/components/Dashboard/InfoDisplay/Assignments/AddAssignments/AssignmentForm.js
front-end/src/components/Dashboard/InfoDisplay/Assignments/AssignmentCard/AssignmentCard.js
front-end/src/components/Dashboard/InfoDisplay/Assignments/AssignmentDetails/AssignmentDetails.js
front-end/src/components/Dashboard/InfoDisplay/Assignments/Assignments.js
front-end/src/components/Dashboard/InfoDisplay/Assignments/TeacherAssignments/TeacherAssignments.js
front-end/src/components/Dashboard/InfoDisplay/Assignments/TeacherAssignments/teacher-assignments.css
front-end/src/components/Dashboard/InfoDisplay/InfoDisplay.js
front-end/src/reducers/assignmentsReducer.js

- [x ] New feature (non-breaking change which adds functionality)
* Working in browser
- [ x] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] My changes generate no new warnings

Teacher assignments list

---

server/models/Assignment.js

Fixed accidental duplication of mongoose schema key when resolving merge conflicts

fix duplicate key

---

apidoc/api_data.js
apidoc/api_data.json
apidoc/api_project.js
apidoc/api_project.json
server/controllers/studentController.js
server/controllers/teacherController.js
server/controllers/userController.js
server/models/Assignment.js
server/routes/teacherRoutes.js
tests/Assignment.test.js
tests/teacherController.test.js

Added get teacher assignments route, updated get student assignments route, and cleaned up some error handling

Get teacher assignments route

---

server/controllers/teacherController.js
tests/teacherController.test.js

update emailAssignment route to return the assignment created

---

server/config/index.js
server/models/Teacher.js

fix token email url

---

front-end/src/actions/index.js
front-end/src/components/Dashboard/InfoDisplay/Assignments/AssignmentCard/AssignmentCard.js
front-end/src/components/Dashboard/InfoDisplay/Assignments/AssignmentDetails/AssignmentDetails.js
front-end/src/components/Dashboard/InfoDisplay/Assignments/Assignments.js
front-end/src/components/Dashboard/InfoDisplay/Assignments/TeacherAssignments/TeacherAssignments.js
server/controllers/teacherController.js
server/models/Assignment.js
server/models/Teacher.js
server/routes/teacherRoutes.js

added deleteAssignment actions and connect to the backend

---

apidoc/api_data.js
apidoc/api_data.json
apidoc/api_project.js
apidoc/api_project.json
server/controllers/teacherController.js
server/models/Assignment.js

add fileName field to assignment model

---

front-end/src/components/Dashboard/InfoDisplay/Assignments/AddAssignments/AssignmentForm.js
front-end/src/components/Dashboard/InfoDisplay/Assignments/AssignmentCard/AssignmentCard.js
front-end/src/components/Dashboard/InfoDisplay/Assignments/AssignmentDetails/AssignmentDetails.js

fixed the assignment form and details

---

front-end/src/components/Dashboard/InfoDisplay/Assignments/Assignments.js

fixed the display bug

---

front-end/src/components/Dashboard/Dashboard.js
front-end/src/components/Dashboard/InfoDisplay/Assignments/AddAssignments/AssignmentForm.js
front-end/src/components/Dashboard/InfoDisplay/Assignments/AddAssignments/assignment-form.css
front-end/src/components/Navbar/signInSignUp.js

CSS styling to assignment form

---

front-end/src/actions/index.js
front-end/src/components/Dashboard/Dashboard.js
front-end/src/components/Navbar/signInSignUp.js

changed the menu to navbar

---

apidoc/api_data.js
apidoc/api_data.json
apidoc/api_project.js
apidoc/api_project.json
server/controllers/studentController.js
server/controllers/teacherController.js
server/models/Teacher.js

Assignments will now automatically be registered to a student if their email already exists. (Will add more tests when our MVP is good to go)

Updated assignment email routes

---

front-end/src/actions/index.js
front-end/src/components/ClaimToken/ClaimToken.js
front-end/src/components/Dashboard/InfoDisplay/Assignments/AddAssignments/AssignmentForm.js
front-end/src/components/Dashboard/InfoDisplay/Assignments/AssignmentCard/AssignmentCard.js
front-end/src/components/Dashboard/InfoDisplay/Assignments/Assignments.js
front-end/src/components/Dashboard/InfoDisplay/InfoDisplay.js
front-end/src/components/Dashboard/InfoDisplay/StudentAssignments/StudentAssignment.js
front-end/src/components/Navbar/navbar.css
front-end/src/components/Navbar/signInSignUp.js
front-end/src/reducers/assignmentsReducer.js
front-end/src/routes/index.js
server/controllers/teacherController.js
server/models/User.js

frontend bug fixes

---

front-end/src/actions/index.js
front-end/src/components/Dashboard/InfoDisplay/Assignments/AddAssignments/AssignmentForm.js
front-end/src/components/Dashboard/InfoDisplay/Assignments/AssignmentCard/AssignmentCard.js
front-end/src/components/Dashboard/InfoDisplay/Assignments/AssignmentDetails/AssignmentDetails.js
front-end/src/components/Dashboard/InfoDisplay/Assignments/TeacherAssignments/TeacherAssignments.js
front-end/src/components/Dashboard/InfoDisplay/Billing/CheckoutForm.js
front-end/src/components/Dashboard/InfoDisplay/Billing/billing.css
front-end/src/components/Dashboard/InfoDisplay/InfoDisplay.js
front-end/src/components/Dashboard/InfoDisplay/StudentAssignments/CheckboxForm.js
front-end/src/components/Dashboard/InfoDisplay/StudentAssignments/StudentAssignment.js
server/controllers/studentController.js
server/models/Assignment.js
server/routes/studentRoutes.js
tests/testDataFactories.js

Added updateAssignment days in student assignment detail page

---

front-end/src/components/Dashboard/InfoDisplay/Assignments/AssignmentCard/AssignmentCard.js
front-end/src/components/Dashboard/InfoDisplay/Assignments/AssignmentDetails/AssignmentDetails.js
front-end/src/components/Dashboard/InfoDisplay/Assignments/TeacherAssignments/TeacherAssignments.js
front-end/src/components/Dashboard/InfoDisplay/InfoDisplay.js
front-end/src/components/Dashboard/InfoDisplay/StudentAssignments/CheckboxForm.js
front-end/src/components/Dashboard/InfoDisplay/StudentAssignments/StudentAssignment.js
server/models/AssignmentProgress.js

Modified the frontend

---

server/controllers/studentController.js
server/controllers/teacherController.js
server/routes/teacherRoutes.js

Add getAssignmentById routes for teachers (includes each student's progress)

getAssignmentById (teacher)

---

front-end/src/components/Dashboard/InfoDisplay/Assignments/AddAssignments/AssignmentForm.js

…mages
- [ x] New feature (non-breaking change which adds functionality)
*Tested in the browser
- [x ] I have performed a self-review of my own code
- [x ] My changes generate no new warnings

Dropzone files

---

front-end/src/components/Dashboard/InfoDisplay/StudentAssignments/StudentAssignment.js
front-end/src/components/Dashboard/InfoDisplay/StudentAssignments/studentassignment.css
front-end/src/components/Signup/SignUp.js

fixed checkboxes css style on student assignments page

---

front-end/src/components/Dashboard/InfoDisplay/Assignments/AddAssignments/AssignmentForm.js
front-end/src/components/Dashboard/InfoDisplay/Assignments/AddAssignments/assignment-form.css
front-end/src/components/Dashboard/InfoDisplay/InfoDisplay.js

- [ x] Bug fix (non-breaking change which fixes an issue)
* Visually in the browser
- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] My changes generate no new warnings

Assignment name upload image alignment

---

front-end/package.json
front-end/public/index.html
front-end/src/components/Dashboard/InfoDisplay/Assignments/AddAssignments/AssignmentForm.js
front-end/src/components/Dashboard/InfoDisplay/Assignments/AddAssignments/assignment-form.css
front-end/src/components/Dashboard/InfoDisplay/Billing/billing.css
front-end/src/components/Dashboard/InfoDisplay/Billing/index.js
front-end/src/components/Dashboard/InfoDisplay/InfoDisplay.js
front-end/src/components/Dashboard/InfoDisplay/StudentAssignments/CheckboxForm.js
front-end/src/components/Dashboard/InfoDisplay/StudentAssignments/StudentAssignment.js
front-end/src/components/Dashboard/InfoDisplay/StudentAssignments/studentassignment.css
front-end/src/components/Dashboard/InfoDisplay/info-display.css
front-end/src/components/Navbar/signInSignUp.js
front-end/yarn.lock

- [x ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
* Tested in the browser
- [x ] I have performed a self-review of my own code
- [x ] My changes generate no new warnings

Small bug fixes

---

front-end/src/components/Dashboard/InfoDisplay/Assignments/TeacherAssignments/TeacherAssignments.js

added unclaim lists to teacherassighments

---

front-end/src/actions/index.js
front-end/src/components/Dashboard/InfoDisplay/Assignments/AddAssignments/AssignmentForm.js
front-end/src/components/Dashboard/InfoDisplay/Assignments/TeacherAssignments/TeacherAssignments.js
front-end/src/components/Dashboard/InfoDisplay/StudentAssignments/CheckboxForm.js
front-end/src/components/Dashboard/InfoDisplay/StudentAssignments/StudentAssignment.js
front-end/src/components/Dashboard/InfoDisplay/UserSettings/UserSettings.js

fixed settings page redirection and added notification

---

front-end/src/components/Dashboard/InfoDisplay/Assignments/TeacherAssignments/TeacherAssignments.js

changed the text on teacher assignments list

---

README.md
front-end/yarn.lock
package.json
server/models/User.js
tests/User.test.js
yarn.lock

Cleaned up some code in the User model, changed bcrypt to be asynchronous, fixed a bug where validation errors were not displaying on the user settings page, and added a codeship badge to the README

Code cleanup
